server:
  port: 8888

base:
  datasource:
    jdbc-url: jdbc:mysql://106.15.192.244:3306/nice_day?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ysh@131021

login:
  password:
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAI82RZbRLegT+WNMhZXghnUkids2cyXNrNCMQTSQAF6jLI5g1XhiDssosGnlH/N9pgv9v/1nNpPz4mCUU1Ku9tE8BZ3GTP23gvnLlix89RyIZ6dMT9v60kIqGXFPu65DBHFz1ETpvZYS/stO4LpGrBGYfFS8AK45gEzaPl3xTBBXAgMBAAECgYA6FcQR0JOy/m73BHFmAaPnXUOAosv/ODVwfIJx5DoSKFKJCONsKTFg2wb6XFEiPAMd9/RnvfYX+iIGFALblVVLmpXwIy1KdKVoi6LccFLpH5aEjN0021pxunsgZpgTOZUDTDgK+4vaJ67eJ/PJO606Vq+g2uSVF3Dl6+nBnHYeaQJBAMOu2qf5OJi9nVMJ1+8IChAh35YviTPv08yBJ2fa3mPZHrct4uT8oSBUIbkGyXGZ90980lxLmRitAxNRKKoppZsCQQC7Wvuy+gXXOVhDAX/kT+3vUvarEApFEPApmU0TuSdOAmmAkaBTN/Wny6Zjvfr4H3Xsoz/RrPkywhzcNFZRzGn1AkAkeNeqTSo+VcEX9BK6K55siVO6E1wYQRAR4tSsZ7/hjltKOxQ6J9gERYoPiXNMaC0PNK2kpDaBweV72TmiFacXAkA2zAWR806CBGOsNWQSgs40kS9UGPzn9mxHvm6sthqo1kvFLtKVhGh1Czs/MPGWYJ08+QJRcSXxkpSeUzBr/D2BAkEAkjKF1jEWpcGrtrMq8pT2gKJNcAmXM565RRqvEZNWrdKnTtW24BjdXHoiAIo9rfAOU8IUp7ig1+I+kzhizvMCuQ==